//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiletAtolyesi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int Id { get; set; }
        public string AirportCode { get; set; }
        public string AirportName { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public string LocalizedCountryName { get; set; }
        public string CityCode { get; set; }
        public string CityName { get; set; }
        public string LocalizedCityName { get; set; }
        public string StateCode { get; set; }
        public string StateName { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> IfActive { get; set; }
    }
}
